version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk-sender
    ports:
      - '5555:5555'
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin

  redis:
    image: redis:latest
    container_name: vk-sender-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - ./aclfile.conf:/usr/local/etc/redis/aclfile.conf
    command:
      [
        'redis-server',
        '--requirepass',
        'admin',
        '--aclfile',
        '/usr/local/etc/redis/aclfile.conf',
      ]

volumes:
  redis_data:
